import type { NextPage } from "next";
import Head from "next/head";

import styles from "@styles/homePage.module.css";
import Header from "../components/header";
import Cards from "../components/cards";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Super Heroes Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Cards />
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
