CREATE TABLE CLIENTS (
	CLIENT_ID SERIAL PRIMARY KEY,
	CLIENT_EMAIL VARCHAR (60) UNIQUE NOT NULL,
	CLIENT_PASSWORD VARCHAR (60) NOT NULL
);

CREATE TABLE HISTORIES (
	HISTORY_ID SERIAL PRIMARY KEY,
	HISTORY_FROM VARCHAR (3) NOT NULL,
	HISTORY_TO VARCHAR (3) NOT NULL,
	HISTORY_AMOUNT VARCHAR (15) NOT NULL,
	HISTORY_RESULT VARCHAR (15) NOT NULL,
	HISTORY_RATE VARCHAR (15) NOT NULL,
	HISTORY_CREATEDAT VARCHAR (30) NOT NULL,
	CLIENT_ID SERIAL NOT NULL,
	FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID)
);